# Generated by Django 4.1.7 on 2023-02-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GalleryApp', '0003_alter_imagemodel_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='uploaded_by',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
